backend:
  name: github
  repo: ctng8kw2qr-ui/civic-orderism-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "文章"
    folder: "articles"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "栏目", name: "category", widget: "string" }
      - { label: "摘要", name: "description", widget: "text" }
      - { label: "正文", name: "body", widget: "markdown" }
